version: '3.8'

services:
  # Meeting Bot - Main recording bot
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: meet-teams-bot:latest
    container_name: meet-teams-bot
    ports:
      - "3000:3000"    # API port
      - "5900:5900"    # VNC port for debugging
    volumes:
      - ./recordings:/app/data
    environment:
      - RECORDING=true
      - DEBUG=false
      - DEBUG_LOGS=false
      - SERVERLESS=true
      - NODE_ENV=production
    stdin_open: true
    tty: true
    restart: unless-stopped
    # Uncomment to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 4G
    #     reservations:
    #       cpus: '1'
    #       memory: 2G

  # Scheduler - Job orchestration API
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    image: meet-teams-bot-scheduler:latest
    container_name: meet-teams-bot-scheduler
    ports:
      - "3001:3000"    # Scheduler API on different port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker/Podman access
      - ./recordings:/app/recordings
    environment:
      - PORT=3000
      - PLATFORM=docker
      - CONTAINER_ENGINE=docker
      - AUTO_DETECT_ENGINE=true
      - SCHEDULER_MAX_CONCURRENT_JOBS=10
      - SCHEDULER_POLLING_INTERVAL=5000
      - SCHEDULER_CONTAINER_IMAGE=meet-teams-bot:latest
      - SCHEDULER_DEFAULT_CPU=1
      - SCHEDULER_DEFAULT_MEMORY=2Gi
      - RECORDINGS_PATH=/app/recordings
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - bot
    # Uncomment to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 1G
    #     reservations:
    #       cpus: '0.5'
    #       memory: 512M

volumes:
  recordings:
    driver: local

networks:
  default:
    name: meet-teams-bot-network
