version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: meeting-bot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - scheduler
    networks:
      - meeting-bot-network
    labels:
      - "com.meeting-bot.service=nginx"
      - "com.meeting-bot.version=latest"

  scheduler:
    image: skyfernaic01.azurecr.io/meeting-bot-scheduler:latest
    container_name: meeting-bot-scheduler
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - CONTAINER_ADAPTER=azure
      # Azure credentials for Azure Container Jobs
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_RESOURCE_GROUP=${AZURE_RESOURCE_GROUP}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      # Azure Container App Job configuration
      - AZURE_CONTAINER_APP_JOB_NAME=${AZURE_CONTAINER_APP_JOB_NAME}
      - AZURE_LOCATION=${AZURE_LOCATION:-uksouth}
      # Azure Container Registry credentials
      - ACR_LOGIN_SERVER=${ACR_LOGIN_SERVER:-skyfernaic01.azurecr.io}
      - ACR_USERNAME=${ACR_USERNAME}
      - ACR_PASSWORD=${ACR_PASSWORD}
      # Bot container image to deploy on Azure
      - CONTAINER_IMAGE=${CONTAINER_IMAGE:-skyfernaic01.azurecr.io/meet-teams-bot:latest}
    volumes:
      # Persistent storage for job data
      - ./data:/app/data
      # Logs directory
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - meeting-bot-network
    labels:
      - "com.meeting-bot.service=scheduler"
      - "com.meeting-bot.version=latest"

networks:
  meeting-bot-network:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local
